### PR TITLE
refactor(consumer): simplify onData method

### PR DESCRIPTION
**Pull request by JKRhb**
In this PR, I started the process of refactoring the `onData` method in the consumer, which is currently very complicated. There are still a couple of things to do, so that I opened the PR as a draft for now.

### CODE REVIEW

**Comment by JKRhb** [comment]
@tanim-ics I think this PR is actually already ready for an initial review :)

**Review by tanim-ics — APPROVED** [review]

**Review by tanim-ics — APPROVED** [review]

**Comment by tanim-ics** [comment]
We need to rename a few function names and need to make the code independent of frame type data

**Comment by JKRhb** [comment]
> We need to rename a few function names and need to make the code independent of frame type data


Do you have suggestions for the renaming? If so, maybe you could add them as a comment in the "Files changed" tab? :)

**Comment by JKRhb** [comment]
I think this PR can be considered superseded by #44 and #46. In the future, we need to make sure that PRs don't become stale like this one did.

**Pull request closed without merging**
