### PR TITLE
refactor: rework project structure

### PR DESCRIPTION
**Pull request by JKRhb**
As previously discussed, this PR refines the overall project structure, splitting the library into an `include` directory with the actual library and an `examples` directory with the IceFlow applications. It also adds the ability to install the library using `sudo make install`.

Before merging, `install.md` needs to be somewhat adjusted, but I think the PR should already be ready for review.

### CODE REVIEW

**Comment by JKRhb** [comment]
After conducting some more research regarding CMake best practices, I renamed the `examples` folder to `apps`, which I found a bit more fitting for our IceFlow applications.

**Comment by JKRhb** [comment]
@tanim-ics I made a couple of additional minor adjustments. Apart from updating the `install.md` file, this PR should now be actually be ready for a review.

**Review by tanim-ics — APPROVED** [review]

**Comment by JKRhb** [comment]
Thank you for your approval, @tanim-ics :) I will merge the PR already and adjust the install instructions in a follow-up PR. For the most part, the instructions should still be valid, it is probably mostly the `sudo make install` that needs to be added somewhere.

**Comment by tanim-ics** [comment]
> Thank you for your approval, @tanim-ics :) I will merge the PR already and adjust the install instructions in a follow-up PR. For the most part, the instructions should still be valid, it is probably mostly the `sudo make install` that needs to be added somewhere.

I did not get the "sudo make install" part.

**Comment by JKRhb** [comment]
> I did not get the "sudo make install" part.

With the new structure, you can actually install iceflow as a library instead of using it only for the example applications. So similar to ndn-cxx, you can invoke `sudo make install` to copy the header files to your "global" include directory, like so:

```sh
$ sudo make install                                                                                                 
[ 16%] Built target imagesource
[ 33%] Built target peoplecounter
[ 50%] Built target facedetection
[ 66%] Built target agedetection
[ 83%] Built target genderdetection
[100%] Built target aggregate
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/iceflow/block.hpp
-- Installing: /usr/local/include/iceflow/consumer-tlv.hpp
-- Installing: /usr/local/include/iceflow/content-type-value.hpp
-- Installing: /usr/local/include/iceflow/data.hpp
-- Installing: /usr/local/include/iceflow/logger.hpp
-- Installing: /usr/local/include/iceflow/measurements.hpp
-- Installing: /usr/local/include/iceflow/producer-tlv.hpp
-- Installing: /usr/local/include/iceflow/ringbuffer.hpp
-- Installing: /usr/local/include/iceflow/typed-data.hpp
-- Installing: /usr/local/lib/iceflow/cmake/iceflow-config.cmake
-- Installing: /usr/local/lib/iceflow/cmake/IceFlow.cmake
```

I will add that to the documentation in a follow-up PR.

**Comment by tanim-ics** [comment]
Ok, I got it now. Thanks, @JKRhb

**Pull request merged**
